[package]
name = "aoc19"
version = "0.1.0"
authors = ["Max Weber <mii7303@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"

strum = "0.16.0"
strum_macros = "0.16.0"

lazy_static = "1.4.0"

regex = "1"

num = "0.2"