[package]
name = "aoc24"
version = "0.1.0"
authors = ["Max Weber <mii7303@gmail.com>"]
edition = "2021"


[profile.release]
opt-level = 3
lto = "fat"
debug = true


[dependencies]
aoc-helper = { path = "../aoc-helper/aoc-helper" }
regex = "1"
memchr = "2.7.4"
strength_reduce = "0.2.4"
num = "0.4.3"