[package]
name = "aoc-helper-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.87"
proc-macro2 = "1.0.89"
quote = "1.0.37"
once_cell = "1.20.2"
regex = "1.11.1"